### ISSUE TITLE
Files missing from private folder

### ISSUE THREAD

**Issue by tassosgolnas** [keybase/book-content#106]
I know this sounds a bit weird, but I have a very strong suspicion that some of files are missing from a sub-folder in my private folder.
I haven't accessed that sub-folder in some months, so I am confident that I didn't delete anything (at least on purpose).

Is there a way to find out when those files were deleted? (I doubt it, but I figured I might just ask).

**Comment by heronhaye** [comment]
If the files were deleted in the last 2 weeks, they might be able to be recovered using `keybase fs recover`. If you just want to find the history, try `keybase fs history`. Hope this helps.

**Comment by tassosgolnas** [comment]
Thank you. Unfortunately, it seems these files went missing longer than two weeks.
