### ISSUE TITLE
How do I export my keybase wallet?

### ISSUE THREAD

**Issue by oilers** [keybase/book-content#124]
I have some XLM in my account, and it says I should export my balances, so I created a wallet with another service, but I don't see how I can move the XLM between wallets. If I go to receive XLM I get a QR code that I don't know what to do with. If I try and import the wallet it wants a recovery passphrase or google drive access. And on the keybase side, I don't see any way to send it via the website or app.

**Comment by oilers** [comment]
Turns out it was an issue with the company I was trying to export too, they don't support that kind of transfer. Using a different platform, I was able to transfer fairly easily. Crypto.com DeFi wallet does not allow that kind of transfer

**Comment by Denyslav** [comment]
I have same issue, where and how did you transfer it? You can send me PM, thank you.

**Comment by oilers** [comment]
So I created an Exodus wallet and was able to transfer the SLM into that wallet. I don't remember the specific steps, but I don't recall them being too difficult with the wallet key from keybase.

**Comment by Denyslav** [comment]
Thanks, I'll try that. I tried on Coinbase and couldn't
