### ISSUE TITLE
How to recover/reuse an account

### ISSUE THREAD

**Issue by qudongfang** [keybase/book-content#57]
How to recover/reuse an account?

**Comment by chindraba-work** [comment]
Reuse: None. Simple, plain and absolute based on how the system is built.

Recover: Depends on the situation. 

If you have a paper key, which you should have made, and will make next time if you didn't, you can use the paper key to authorize a new device, and pick  up where you left off.

If you have lost, or deleted, the paper keys, and have no remaining devices authorized, I don't think it's possible to recover the account, by name, as that's basically the same thing as reusing the account. A "reset" might be a possibility, if you have access to the phone or email that created the account. Not sure if, or how, that part works.

I know it's impossible to recover, under any circumstances, the old chats, and the Stellar wallet. All the things from the account are signed, and encrypted, by the keys from the old devices, and it's not possible to unencrypt them without that key. At least not without a quantum computer anyway. There is no "backdoor" or "super" key built into the system which would allow "opening" account data from outside that account.
