### ISSUE TITLE
Error 404 in some pages of https://book.keybase.io/docs/

### ISSUE THREAD

**Issue by PhantomHydraPH** [keybase/book-content#71]
Get error 404 in some pages, like [https://book.keybase.io/docs/coinflip](https://book.keybase.io/docs/coinflip)

**Comment by secur3gamer** [comment]
Can confirm, came to report [https://book.keybase.io/docs/git](https://book.keybase.io/docs/git) - should be [https://book.keybase.io/git](https://book.keybase.io/git)

**Comment by dolmen** [comment]
Related: #46

**Comment by dolmen** [comment]
Related: #41

**Comment by dolmen** [comment]
It looks like there is an alternate version of the Keybase Book here: https://book.keybase.io/

The question is why does the footer of https://keybase.io/ links to https://keybase.io/docs which redirects to https://book.keybase.io/docs which has so many broken links.

**Comment by heronhaye** [comment]
Hi, where do you see the link to the coinflip doc?
