### ISSUE TITLE
Mastodon verify not working anymore

### ISSUE THREAD

**Issue by Maybach91** [keybase/book-content#93]
I got a email that my verification just broke. And i cannot revalidate it (post is still online and public). 
Also re-adding the mastodon profile gives me a link which end up in a 404, to verify.

![image](https://user-images.githubusercontent.com/1867543/145033345-981a87af-cb9d-4f39-a361-e9f938819b7b.png)
![image](https://user-images.githubusercontent.com/1867543/145033390-0db1cd57-3104-4f12-b0dd-f073534e618e.png)
https://mastodon.social/settings/identity_proofs/new

I think mastodon removed this setting to identify? I cannot find it in the settings, but i’m not sure if it was there before.

**Comment by ajft** [comment]
https://github.com/mastodon/mastodon/pull/17045 - "Keybase has been acquired by Zoom and has, to my knowledge, stopped development of its platform. Also, the manual approval for Mastodon servers that they insisted on doing on their side never scaled and created frustration on our side. Also, Keybase never solved the verification problem in the way that people expected it to be solved, i.e. I still won't know if I'm looking at the real, famous John Smith, or just someone who claimed the john.smith handle on Keybase. For all other purposes it doesn't do anything that our own link verification mechanism doesn't do already."

**Comment by Maybach91** [comment]
> https://github.com/mastodon/mastodon/pull/17045 - "Keybase has been acquired by Zoom and has, to my knowledge, stopped development of its platform. Also, the manual approval for Mastodon servers that they insisted on doing on their side never scaled and created frustration on our side. Also, Keybase never solved the verification problem in the way that people expected it to be solved, i.e. I still won't know if I'm looking at the real, famous John Smith, or just someone who claimed the john.smith handle on Keybase. For all other purposes it doesn't do anything that our own link verification mechanism doesn't do already."



Thank you for pointing out! I found the correct repository as well. 😅
